window.INITIAL_STUDENTS = [
  {
    "id": "aluno-4",
    "aluno": "Felipao",
    "modalidade": "Muay Thai",
    "horario": "08:00",
    "turma": "Muay Thai 08:00",
    "cobrado": "Nao",
    "pago": "Sim",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-5",
    "aluno": "Nanny",
    "modalidade": "Muay Thai",
    "horario": "08:00",
    "turma": "Muay Thai 08:00",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": "dia  25"
  },
  {
    "id": "aluno-6",
    "aluno": "Maria filha",
    "modalidade": "Muay Thai",
    "horario": "08:00",
    "turma": "Muay Thai 08:00",
    "cobrado": "Nao",
    "pago": "Sim",
    "valor": 70.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-7",
    "aluno": "Laura",
    "modalidade": "Muay Thai",
    "horario": "08:00",
    "turma": "Muay Thai 08:00",
    "cobrado": "Nao",
    "pago": "Sim",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-8",
    "aluno": "Milena",
    "modalidade": "Muay Thai",
    "horario": "08:00",
    "turma": "Muay Thai 08:00",
    "cobrado": "Nao",
    "pago": "Sim",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-9",
    "aluno": "Dihandra",
    "modalidade": "Muay Thai",
    "horario": "08:00",
    "turma": "Muay Thai 08:00",
    "cobrado": "Nao",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-10",
    "aluno": "Leandro",
    "modalidade": "Boxe",
    "horario": "16:30",
    "turma": "Boxe 16:30",
    "cobrado": "Nao",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-11",
    "aluno": "Lucas",
    "modalidade": "Boxe",
    "horario": "16:30",
    "turma": "Boxe 16:30",
    "cobrado": "Nao",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-12",
    "aluno": "Nichollas nicu",
    "modalidade": "Boxe",
    "horario": "16:30",
    "turma": "Boxe 16:30",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-13",
    "aluno": "Matheus Santos mendes",
    "modalidade": "Boxe",
    "horario": "16:30",
    "turma": "Boxe 16:30",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-14",
    "aluno": "Emanuel",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-15",
    "aluno": "Giovana Caputo",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-16",
    "aluno": "Bernardo",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-17",
    "aluno": "Heitor",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-18",
    "aluno": "Arthur",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-19",
    "aluno": "Samuel",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-20",
    "aluno": "Victoria",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-21",
    "aluno": "Rafael",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-22",
    "aluno": "Fernando",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-23",
    "aluno": "Matteo",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-24",
    "aluno": "Karen",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-25",
    "aluno": "Francisco",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-26",
    "aluno": "Natalia",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-27",
    "aluno": "Mari",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-28",
    "aluno": "Murilo",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-29",
    "aluno": "Paulinha",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-30",
    "aluno": "Davi",
    "modalidade": "Muay Thai",
    "horario": "17:40",
    "turma": "Muay Thai 17:40",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 70.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-31",
    "aluno": "Ana",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 70.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-32",
    "aluno": "Peu",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-33",
    "aluno": "Rhasmin",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-34",
    "aluno": "Thiago da taci",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-35",
    "aluno": "Leonardo",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-36",
    "aluno": "Fabricio",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-37",
    "aluno": "Eduardo",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": "TP "
  },
  {
    "id": "aluno-38",
    "aluno": "Victor",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-39",
    "aluno": "Nicolas albuquerque",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": "2 meses inadimplente"
  },
  {
    "id": "aluno-40",
    "aluno": "Thiago",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 60.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": "TP "
  },
  {
    "id": "aluno-41",
    "aluno": "Vinicius",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 70.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-42",
    "aluno": "Smaile",
    "modalidade": "Muay Thai",
    "horario": "19:00:00",
    "turma": "Muay Thai 19:00:00",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-43",
    "aluno": "Larissa",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-44",
    "aluno": "Rhasmin",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-45",
    "aluno": "Flavio",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": " enviou 100,00 a mais da graduação"
  },
  {
    "id": "aluno-46",
    "aluno": "Murilo (Vanderlei)",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-47",
    "aluno": "Giovanna",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Nao",
    "valor": 70.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  },
  {
    "id": "aluno-48",
    "aluno": "Verônica",
    "modalidade": "Muay Thai",
    "horario": "19:00",
    "turma": "Muay Thai 19:00",
    "cobrado": "Sim",
    "pago": "Sim",
    "valor": 80.0,
    "forma": "Pix/Outros",
    "categoria": "Mensal",
    "observacao": ""
  }
];
